python3 get_train_data.py \
    --f_r=/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/saas/imbot/data/d0829/IM模型最新训练数据2023_07_20副本-训练数据.csv \
    --problem_type=single_label_classification \
    --f_train=/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/saas/imbot/data/d0829/hf_train_data/train_d0823.json \
    --f_eval=/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/saas/imbot/data/d0829/hf_train_data/eval_d0823.json \
    --f_test=/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/saas/imbot/data/d0829/hf_train_data/test_d0823.json \
    --f_config=/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/saas/imbot/data/label2id.json \
    --f_ner_dict=/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/saas/imbot/data/ner_dict2.json \
    --f_ner_config=/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/saas/imbot/data/ner_label2id.json \
    --f_data_count=/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/saas/imbot/data/d0829/hf_train_data/data_count.csv \
    --f_data_len=/mnt/bn/fulei-v6-hl-nas-mlx/mlx/workspace/saas/imbot/data/d0829/hf_train_data/data_len.csv
